---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jigangyu.
--- DateTime: 2019/11/7 9:05 上午
---
local JSON = require("cjson")

function bullshitGenerator(title, length)
    local file = io.open("bullshitData.json", "r")
    io.input(file)
    local bullshitData = JSON.decode(io.read("*a"))
    local mingrenmingyan = bullshitData['famous']
    local qianmiandianhua = bullshitData['before']
    local houmiandianhua = bullshitData['after']
    local feihua = bullshitData['bosh']
    local chongfudu = 2
    local f = assert(io.open(title ..os.time().. '.txt', "w"))
    f:write(title .. '\r\n')

    local function random_choose(shuzu)
        math.randomseed(tostring(os.time()):reverse():sub(1, 6))
        return (shuzu[math.random(1, #shuzu)])
    end
    local function newMingrenmingyan()
        local str = random_choose(mingrenmingyan)
        str = string.gsub(str, "a", random_choose(qianmiandianhua))
        str = string.gsub(str, "b", random_choose(houmiandianhua))
        return str
    end
    local function newParagraph()
        local str = "。\r\n    "--四个半角空格
        return str
    end

    local tmp = ""
    while (string.len(tmp) < length+0) do
        local fenzhi = math.random(1, 100)
        if (fenzhi < 5) then
            tmp = tmp .. newParagraph()
        elseif (fenzhi < 20) then
            tmp=tmp..newMingrenmingyan()
        else
            tmp=tmp..random_choose(feihua)
        end
    end
    f:write(tmp)
    f:close()
end

print("输入文章主题：")
local title = io.read()
print("输入字数：")
local length = io.read()
bullshitGenerator(title, length)
